### ISSUE TITLE
Map support for Dart VM

### ISSUE THREAD

**Issue by fakalit** [ApolloVM/apollovm_dart#4]
First of all thank you for this amazing project. There is nothing else out there with a similar feature set for the dart ecosystem.

It looks like while we can use the "List<>" type in our parsed code, if we use "Map<,>" it fails to load.

I'm not sure what other limitations regarding type are there, but Map is a critical one since it can represent complex object structures, so its addition would be greatly appreciated.

**Comment by gmpassos** [comment]
Thanks, I hope that you enjoy the project.

The `Dart` parser of `ApolloVM` is not 100% complete yet, and is not supporting `Map`s.

I have planned to improve it in the next months. If you wish to contribute just fork the project and send a `pull request`. Also you can help adding some tests, since this helps a lot when new features are being developed.

Best regards.

**Comment by gmpassos** [comment]
`Map` support for Dart will be in the next version.

**Comment by gmpassos** [comment]
Check the new release:
`apollovm: ^0.0.35`

With support for `List` and `Map` literals.
